# Generated by Django 4.2.1 on 2024-07-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_on"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["created_on"]},
        ),
        migrations.AddField(
            model_name="comment",
            name="challenge",
            field=models.FloatField(default=0.0),
        ),
    ]
