# Generated by Django 4.2.1 on 2024-07-04 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_comment_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="challenge",
        ),
    ]
